name: butler-server
type: generic
docroot: .
webserver_type: generic
xdebug_enabled: false
additional_hostnames:
  - "butler-server"
  - "api.butler-server"
additional_fqdns: []
database:
    type: postgres
    version: "17"
use_dns_when_possible: true
web_environment:
    - POSTGRES_HOST=db
    - POSTGRES_PORT=5432
    - POSTGRES_DB=db
    - POSTGRES_USER=db
    - POSTGRES_PASSWORD=db
    - MINIO_ENDPOINT=minio:9000
    - MINIO_PUBLIC_ENDPOINT=https://storage.butler-server.ddev.site
    - MINIO_ACCESS_KEY=ddevminio
    - MINIO_SECRET_KEY=ddevminio
    - MINIO_BUCKET=butler-storage
    - MINIO_USE_SSL=false
corepack_enable: false
# Custom web build with latest Go and tools
webimage_extra_packages: []
web_extra_exposed_ports:
  - name: butler-api
    container_port: 8080
    http_port: 80
    https_port: 443
web_extra_daemons:
  - name: butler-server
    command: "/var/www/html/butler-server"
    directory: /var/www/html
hooks:
  pre-start:
    - exec-host: "go build -v -o butler-server ."
  post-start:
    - exec: "echo 'Setting up MinIO client alias...'"
    - exec: "mc alias set minio http://minio:9000 ddevminio ddevminio || echo 'MinIO alias setup failed'"
    - exec: "echo 'Creating MinIO bucket...'"
    - exec: "mc mb minio/butler-storage || echo 'Bucket already exists or will be created by application'"
    - exec: "echo 'Setting bucket policy for public read access...'"
    - exec: "mc anonymous set download minio/butler-storage || echo 'Policy will be set by application'"
